[package]
name = "sheldon"
version = "0.6.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"
description = "Fast, configurable, shell plugin manager."
documentation = "https://rossmacarthur.github.io/sheldon"
readme = "README.md"
homepage = "https://github.com/rossmacarthur/sheldon"
repository = "https://github.com/rossmacarthur/sheldon"
license = "MIT OR Apache-2.0"
keywords = ["shell", "plugin", "manager", "zsh", "bash"]
categories = ["command-line-utilities"]
build = "build.rs"
include = ["src/**/*", "LICENSE-*", "README.md", "build.rs"]

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.33"
atty = "0.2.14"
casual = "0.2.0"
clap = { version = "3.0.0-beta.2", features = ["derive"] }
curl = "0.4.34"
fs2 = "0.4.3"
git2 = "0.13.12"
globwalk = "0.8.0"
handlebars = "3.5.0"
home = "0.5.3"
indexmap = { version = "1.6.0", features = ["serde-1"] }
itertools = "0.9.0"
maplit = "1.0.2"
once_cell = "1.4.1"
regex = "1.4.1"
regex-macro = "0.1.1"
scoped_threadpool = "0.1.9"
serde = { version = "1.0.117", features = ["derive"] }
thiserror = "1.0.21"
toml = { version = "0.5.7", features = ["preserve_order"] }
toml_edit = "0.2.0"
url = { version = "2.1.1", features = ["serde"] }
walkdir = "2.3.1"
which = { version = "4.0.2", default-features = false }

[build-dependencies]
anyhow = "1.0.32"
chrono = "0.4.15"
git2 = "0.13.8"
rustc_version = "0.3.0"

[dev-dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
pretty_assertions = "0.6.1"
tempfile = "3.1.0"

[workspace]
members = ["tools/generate-readme"]
